<Project Sdk="Microsoft.NET.Sdk">
    <Sdk Name="Aspire.AppHost.Sdk" Version="9.1.0" />

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.AppHost" Version="9.1.0" />
    </ItemGroup>

    <!--
        Project references to each service are added here once
        they are ready to be orchestrated. Example:

        <ProjectReference Include="..\UserService\src\Api\Api.csproj" />
        <ProjectReference Include="..\DND5EHandler\src\Api\Api.csproj" />
        <ProjectReference Include="..\CharacterHandler\src\Api\Api.csproj" />
        <ProjectReference Include="..\Gateway\src\Api.csproj" />
    -->

</Project>
